version: '3.8'
services:
  vlc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vlc
    ports:
      - "8554:8554"
    command:
      - "<some-stream-location>"
      - "--no-audio"
      - "--no-video"
      - "--sout"
      - "#standard{access=http,mux=ts,dst=:8554}"
      - "--no-sout-all"
      - "--sout-keep"
    restart: unless-stopped
