version: '3.8'
services:
  vlc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vlc
    ports:
      - "8554:8554"
    environment:
      - SOURCE_URL=http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4
    command:
      - "${SOURCE_URL}"
      - "--no-audio"
      - "--no-video"
      - "--sout"
      - "#standard{access=http,mux=ts,dst=:8554}"
      - "--no-sout-all"
      - "--sout-keep"
    restart: unless-stopped
